### ISSUE TITLE
SPT Crash OutOfMemoryException 

### ISSUE THREAD

**Issue by Keygaann** [sailro/EscapeFromTarkov-Trainer#410] opened 2023-10-17 18:34 UTC
When I do nothing and the game reaches 15GB RAM use it crashes

I tried in game Auto RAM Cleaner and hitting Esc when RAM use was around 9GB don't work
Memory Cleaner by Koshy John and ISLC also don't work

Task Manager shows me that the RAM has been cleared and yet the game crash without reach 15GB RAM use

Specs
AMD Ryzen 7 5700X
XFX Radeon RX 6700 XT SWFT 309 Gaming 12GB
GoodRam IRDM PRO Deep Black, DDR4, 32 GB, 3600MHz

Logs
EXCEPTION: System.OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) System.Object.__icall_wrapper_ves_icall_object_new_specific(intptr)
  at EFT.Trainer.Features.Players+<>c__DisplayClass78_0.<OnGUI>b__0 (System.ValueTuple`2[T1,T2] bone) [0x00000] in <771236eaadf743f69f44a2d27d12f0bb>:0 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at EFT.Trainer.Features.Players.OnGUI () [0x00241] in <771236eaadf743f69f44a2d27d12f0bb>:0 
2023-10-17 19:55:45.399 +02:00|0.13.5.3.26535|Error|Default| 
EXCEPTION: System.OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) System.String.FastAllocateString(int)
  at System.Text.StringBuilder.ToString () [0x00014] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at EFTConfiguration.EFTConfiguration.<Start>b__31_0 (EFTConfiguration.EFTLogListener+LogData log) [0x00012] in <035cadea2f994d37959dd546b6c5b575>:0 
  at EFTConfiguration.EFTLogListener.LogEvent (System.Object sender, BepInEx.Logging.LogEventArgs eventArgs) [0x00062] in <035cadea2f994d37959dd546b6c5b575>:0 
  at BepInEx.Logging.Logger+LogListenerCollection.SendLogEvent (System.Object sender, BepInEx.Logging.LogEventArgs eventArgs) [0x00012] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
  at BepInEx.Logging.Logger.InternalLogEvent (System.Object sender, BepInEx.Logging.LogEventArgs eventArgs) [0x00000] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
  at BepInEx.Logging.UnityLogSource.UnityLogMessageHandler (System.Object sender, BepInEx.Logging.LogEventArgs eventArgs) [0x0001d] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
  at BepInEx.Logging.UnityLogSource.OnUnityLogMessageReceived (System.String message, System.String stackTrace, UnityEngine.LogType type) [0x0004c] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void_string_string_LogType(string,string,UnityEngine.LogType)
  at UnityEngine.Application.CallLogCallback (System.String logString, System.String stackTrace, UnityEngine.LogType type, System.Boolean invokedOnMainThread) [0x00015] in <ca21460feb9c47d0ac337b9893474cc6>:0

**Comment by sailro** [comment] 2023-10-21 07:42
Dupe of #296. On which map ?

**Closed by sailro** 2023-10-21 07:42 UTC

**Comment by Keygaann** [comment] 2023-10-21 17:10
it crash on Customs Interchange Woods

SPT-AKI 3.7.1
with
EFT Api
KMC Server Value Modifier
Game Panel HUD
Item Info
No Bush ESP
Force Difficulty Setting
Take A Break
Josh Mate's Better Backpacks
Special Slots

Amand Graphics is not instaled

when I run Tarkov without a trainer, the game goes to ~9GB and clears up to 7GB on its own and doesn't crash even after 2-3 hours into raid

I tried to do a clean installation SPT without mods and only the trainer
the game does not crash, but the RAM reaches 98%(27GB) usage then clear ~1GB and again go to 98%
