### ISSUE TITLE
Repeating multiple times cannot localize the installation language

### ISSUE THREAD

**Issue by longdiyushen** [sailro/EscapeFromTarkov-Trainer#615] opened 2024-11-29 11:06 UTC
Compilation failed for master branch.
Warning: no localization support for language 'zh-cn'.
Unable to compile trainer for version 0.14.9.30626

I don't understand, but the English version still works properly,
Please tell me how to install other languages

**Comment by solareon** [comment] 2024-11-29 11:21
Duplicate of https://github.com/sailro/EscapeFromTarkov-Trainer/issues/614. zh-cn is not available for that build via the installer. You need to update to the latest SPT for zh-cn localization.

**Closed by solareon** 2024-11-29 11:21 UTC

**Comment by longdiyushen** [comment] 2024-11-29 11:24
I am a beginner in this field, how can I update it?Where to download the new SPT on the forum

**Comment by solareon** [comment] 2024-11-29 11:40
> I am a beginner in this field, how can I update it?Where to download the new SPT on the forum

from https://sp-tarkov.com/#download ??? You will need to download the latest Tarkov from the BSG launcher

**Comment by longdiyushen** [comment] 2024-11-29 12:00
emm
![没有找到](https://github.com/user-attachments/assets/3b013e1a-a8a7-45b6-af42-ffcd503b9ca2)
m, I don't understand what's missing

**Comment by solareon** [comment] 2024-11-29 13:51
> emm ![没有找到](https://private-user-images.githubusercontent.com/190087077/391077845-3b013e1a-a8a7-45b6-af42-ffcd503b9ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODE5NjEsIm5iZiI6MTczMjg4MTY2MSwicGF0aCI6Ii8xOTAwODcwNzcvMzkxMDc3ODQ1LTNiMDEzZTFhLWE4YTctNDViNi1hZjQyLWZmY2Q1MDNiOWNhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMjAxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWI2MjhmYjIzMjk2NTM4MDA4YTVlY2NlZWIyNzIzOGE2MzU2OTE1OTg5NmY4ODQ0M2JmZmQ2NzZiYWRiYTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pd32zR3MygzjqZlIJwrnRLGnGMTHjS3ZUgSQESPJzL8) m, I don't understand what's missing

You will need to join the SPT discord and ask. We do not provide support for installing SPT.
