### ISSUE TITLE
Wont install.

### ISSUE THREAD

**Issue by AboPiPs** [sailro/EscapeFromTarkov-Trainer#429] opened 2023-12-24 11:39 UTC
Used to use this trainer before. Now installed Tarkov back again, but wont work with newest version. Wont install. Probably I was just unlucky to download it when Christmas event started. Will use it for AKI not online live. If its a quick fix, could you please update? Have a great Christmas :)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/154736154/0e244840-be70-45a0-b8ac-7599b3704438)

**Comment by solareon** [comment] 2023-12-25 12:51
Dupe of #427

**Closed** 2023-12-25 12:51 UTC
