### ISSUE TITLE
ESP Boxes + aimbot 

### ISSUE THREAD

**Issue by CleanSoftwareSolutions** [sailro/EscapeFromTarkov-Trainer#252] opened 2022-10-13 19:49 UTC
The ESP Boxes are not rendered over their targets and the informations text is just at the bottom of the screen. maybe a resolutionbug? playing on 1440p borderless. also the aimbot seems not to work for me. tried different keys but no one seems to work.

**Comment by sailro** [comment] 2022-10-15 15:23
Probably a duplicate of those:

https://github.com/sailro/EscapeFromTarkov-Trainer/issues/149
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/230

**Closed by sailro** 2022-10-15 15:23 UTC
