### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by DufiwExDev** [sailro/EscapeFromTarkov-Trainer#513] opened 2024-06-02 07:41 UTC
**Describe the bug**
When Pressing 'Right-Alt' the GUI doesn't appear

**To Reproduce**
Compile the source via universal installer and start the game via SPTAKI

**Expected behavior**
The console works but GUI doesn't appear

**Comment by sailro** [comment] 2024-06-02 08:19
dupe of #509

**Closed by sailro** 2024-06-02 08:19 UTC
Labels: duplicate
