### ISSUE TITLE
Issue with 12.12.16778

### ISSUE THREAD

**Issue by BladeOfGodSlayer** [sailro/EscapeFromTarkov-Trainer#223] opened 2022-07-31 13:08 UTC
I installed this trainer on my laptop, it runs perfectly, however, I tried to run this trainer on my PC, shows there is no version for 12.12.16778 
Help
:D

**Comment by sailro** [comment] 2022-07-31 17:54
Dupe of #221

**Closed by sailro** 2022-07-31 17:54 UTC
Labels: duplicate
