### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by swang300** [sailro/EscapeFromTarkov-Trainer#414] opened 2023-11-03 19:28 UTC
It was in a night raid, possibly at or right after I turned thermal off, sniped and thermal on again.  system memory did not run out.

2023-11-03 11:55:34.536 -07:00|0.13.5.3.26535|Error|Default|OutOfMemoryException: Out of memory
GClass681.DistinctBy[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Trainer.Features.PointOfInterests.ProcessDataOnGUI (EFT.Trainer.Features.PointOfInterest[] data) (at <7633090e1a184ca783b7dd99c719606e>:0)
EFT.Trainer.Features.CachableFeature`1[T].OnGUIWhenEnabled () (at <7633090e1a184ca783b7dd99c719606e>:0)
EFT.Trainer.Features.ToggleFeature.OnGUI () (at <7633090e1a184ca783b7dd99c719606e>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class327:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Keygaann** [comment] 2023-11-05 09:24
as a temporary solution, I recommend increasing the virtual memory because committed memory causes crashes
here's a video on how to do it https://www.youtube.com/watch?v=Cb5KjK--170&t=115s&ab_channel=TheMutedGamer

**Comment by sailro** [comment] 2023-11-11 17:59
dupe of #296

**Closed by sailro** 2023-11-11 17:59 UTC
