### ISSUE TITLE
Loot on - Corpse

### ISSUE THREAD

**Issue by andrei-florentin** [sailro/EscapeFromTarkov-Trainer#428] opened 2023-12-23 12:59 UTC
Hello.
I've been enjoying SP Tarkov with this trainer, it makes it really easi to find the hard to loot.
I have an issue and I don't know how to overcome it, any advice is very appreciated.
The issue I have is that if i want to track ledx and type loot on then the UI also will display all corpses,even if they don't have the loot LEDX on them.
After a few minutes it becomes almost imposible to track the loot I want because of the Corpse text?
Is there a way to track loot without displaying the dead bodies/corpses?

**Comment by sailro** [comment] 2023-12-28 16:20
Dupe of #408

Indeed this is something I'm going to have a look.

Not sure yet if it's a bug on our side or spt-aki or tarkov. I will wait for proper support for 0.14.x then I will try to ix this.

Thanks!

**Closed by sailro** 2023-12-28 16:20 UTC
