### ISSUE TITLE
Can't install on SPT-AKI

### ISSUE THREAD

**Issue by MKS1750** [sailro/EscapeFromTarkov-Trainer#437] opened 2024-01-04 07:21 UTC
I open the installer from the folder with SPT-AKI, but the installer wants to install in C:\Battlestate Games\EFT where Tarkov live is located, could you send me or add the file "aki-efttrainer.dll" to Releases? so that I can just put it in the BepInEx\plugins folder

**Comment by sailro** [comment] 2024-01-04 09:20
dupe of #435

**Closed by sailro** 2024-01-04 09:20 UTC
