### ISSUE TITLE
Suggestion for silent aim and aimbot

### ISSUE THREAD

**Issue by UmaPedra** [sailro/EscapeFromTarkov-Trainer#217] opened 2022-07-27 22:19 UTC
I would like to suggest to add a option to change the hit area on aimbot and silent aim

add maybe neck, torso, legs, arm, etc

**Comment by sailro** [comment] 2024-04-08 17:26
dupe of https://github.com/sailro/EscapeFromTarkov-Trainer/issues/75

**Closed by sailro** 2024-04-08 17:26 UTC
Labels: duplicate, enhancement
