### ISSUE TITLE
Player-ESP not disabling

### ISSUE THREAD

**Issue by plxzy255** [sailro/EscapeFromTarkov-Trainer#61] opened 2021-08-30 15:23 UTC
Turning off the Player-ESP isn't doing anything in SPTarkov. I'm trying to make a UpdateWhenDisabled() function in the Players.cs class. Anyways nice code!

**Comment by sailro** [comment] 2021-08-30 15:26
It will work on next raid.

That's because we altered shaders for all players. If we want to handle this scenario, we have to restore original shaders when disabling.

**Comment by sailro** [comment] 2021-09-07 14:36
Dupe of https://github.com/sailro/EscapeFromTarkov-Trainer/issues/40

**Closed by sailro** 2021-09-07 14:36 UTC
Labels: enhancement
